remote: true

experienceLevel:
  internship: true
  entry: false
  associate: true
  mid: false
  senior: false
  director: true
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all_time: false
  month: true
  week: false
  24_hours: true

positions:
  - Software developer

locations:
  - Germany

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:

