remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: true
 executive: true

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: true
 internship: false
 other: true
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Software developer
  - Web developer
  - Javascript developer
  - React developer
  - Magento developer
  - Wordpress developer

locations:
  - United States
  
distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2