remote: true
experienceLevel:
  entry: true
  mid: true
  senior: true
jobTypes:
  full-time: true
  part-time: true
  contract: true

date:
 all time: [true/false]
 month: [true/false]
 week: [true/false]
 24 hours: [true/false]

positions:
  - Software developer

locations:
  - Country1
  - Country2

distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2
