remote: true

experienceLevel:
  entry: true
  associate: false
  mid: true
  senior: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: true
  volunteer: false

date:
  all_time: true
  month: true
  week: true
  24_hours: true

positions:
  - Software developer
  - Web developer
  - Javascript developer
  - React developer
  - Magento developer
  - Wordpress developer

locations:
  - United States
  
distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2

credentialsFilePath: "data_folder/secrets.yaml"  # Path to the secrets file containing credentials

